Repository OWASP/mastg, pull requests merged in 2020-08, with the labels that each got.

#1783 Fix SDK Tools Link
  Document/0x05b-Basic-Security_Testing.md
Labels: Android

#1775 Removing first levels in sections
  Document/0x00-Header.md
  Document/0x01-Foreword.md
  Document/0x02-Frontispiece.md
  Document/0x04-General-Testing-Guide.md
  Document/0x04a-Mobile-App-Taxonomy.md
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x04g-Testing-Cryptography.md
  Document/0x04h-Testing-Code-Quality.md
  Document/0x04i-Testing-user-interaction.md
  Document/0x05-Android-Testing-Guide.md
  Document/0x05a-Platform-Overview.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05d-Testing-Data-Storage.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05f-Testing-Local-Authentication.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x05h-Testing-Platform-Interaction.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06-iOS-Testing-Guide.md
  Document/0x06a-Platform-Overview.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06e-Testing-Cryptography.md
  Document/0x06f-Testing-Local-Authentication.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08-Testing-Tools.md
  Document/0x09-Suggested-Reading.md
  Document/Images/OWASP_logo.png
  README.md
  book.json
  tools/book.json
  tools/generate_document.sh
Labels: org

#1789 #1652 Testing iOS Libraries with objection
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Labels: iOS

#1642 Testing tapjacking/overlay - Issue1103
  Document/0x05h-Testing-Platform-Interaction.md
Labels: Android, Requirement

#1812 Fix dashes, quotes and word-computer
  CONTRIBUTING.md
  Document/0x04a-Mobile-App-Taxonomy.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x04h-Testing-Code-Quality.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05d-Testing-Data-Storage.md
  Document/0x05h-Testing-Platform-Interaction.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08-Testing-Tools.md
  style_guide.md
Labels: org
