Repository OWASP/mastg, pull requests merged in 2022-07, with the labels that each got.

#2134 [Docs] Add more tabs such as talks, donate and news
  docs/assets/donations/donators.png
  docs/assets/donations/mstg_donation_form.png
  docs/assets/donations/owasp_donation_form.png
  docs/donate.md
  docs/javascripts/tablesorts.js
  docs/news.md
  docs/releasing/1_How_to_Release.md
  docs/releasing/2_GitHub_Actions.md
  docs/releasing/3_How_to_Export.md
  docs/talks.md
  mkdocs.yml
Labels: ignore-for-release

#2136 Fix contributing links
  README.md
Labels: ignore-for-release

#2137 Fix Link
  README.md
Labels: ignore-for-release

#2138 Deploy MSTG to mkdocs website
  .github/workflows/build-website.yml
  Document/SUMMARY.md
  docs/donate.md
  docs/news.md
  docs/talks.md
Labels: ignore-for-release

#2140 Restrict Workflows and fix command
  .github/workflows/build-website.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docgenerator.yml
Labels: ignore-for-release

#2143 Fix All Markdown Lint Issues and Broken Links
  .github/workflows/checkLinks.yml
  .github/workflows/checkLint.yml
  .github/workflows/codespell.yml
  .github/workflows/config/mlc_config.json
  .github/workflows/docgenerator.yml
  .markdownlint.json
  .markdownlint.jsonc
  CONTRIBUTING.md
  Crackmes/README.md
  Document/0x02a-Frontispiece.md
  Document/0x02c-Acknowledgements.md
  Document/0x04a-Mobile-App-Taxonomy.md
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x04g-Testing-Cryptography.md
  Document/0x04h-Testing-Code-Quality.md
  Document/0x04i-Testing-User-Privacy-Protection.md
  Document/0x05a-Platform-Overview.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05d-Testing-Data-Storage.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05f-Testing-Local-Authentication.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x05h-Testing-Platform-Interaction.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06a-Platform-Overview.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06e-Testing-Cryptography.md
  Document/0x06f-Testing-Local-Authentication.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08-Testing-Tools.md
  Document/0x09-Suggested-Reading.md
  README.md
  docs/contributing/1_How_Can_You_Contribute.md
  docs/contributing/5_Style_Guide.md
  docs/index.md
  docs/news.md
  docs/talks.md
  tools/README.md
Labels: errata, automation

#2146 Fix adoption table widths
  Document/0x02b-MASVS-MSTG-Adoption.md
Labels: ignore-for-release

#1984 Testing MSTG-PLATFORM-10 (WebViews cleanup)
  Document/0x05h-Testing-Platform-Interaction.md
Labels: MASVS-PLATFORM, tests

#2145 [0x06b] Update Jailbreak Content (by @NowSecure)
  Document/0x06b-Basic-Security-Testing.md
  Document/Images/Chapters/0x06b/UDID-Finder.png
  Document/Images/Chapters/0x06b/finder_ipad_view.png
  Document/Images/Chapters/0x06b/finder_unveil_udid.png
Labels: iOS

#2144 Add FIPS 140-2 validated info for corecrypto
  Document/0x06e-Testing-Cryptography.md
Labels: iOS, MASVS-CRYPTO

#2148 Deploy MASVS to web
  .github/workflows/build-website.yml
  mkdocs.yml
Labels: ignore-for-release

#2149 try fix deploy
  .github/workflows/build-website.yml
Labels: ignore-for-release

#2150 fix repo name
  .github/workflows/build-website.yml
Labels: ignore-for-release

#2151 Add PR-only URL Checker
  .github/workflows/markdown-linter.yml
  .github/workflows/spell-checker.yml
  .github/workflows/url-checker-pr.yml
  .github/workflows/url-checker.yml
Labels: ignore-for-release

#2152 Fix Actions Status Badges
  Document/0x08-Testing-Tools.md
  README.md
Labels: ignore-for-release

#2154 Web - Create General, Android and iOS sections
  .github/workflows/build-website.yml
Labels: ignore-for-release

#2155 fix png
  docs/assets/starring.png
  docs/contributing/1_How_Can_You_Contribute.md
Labels: ignore-for-release

#2042 Fix Network Security Testing on Android and iOS (by @NowSecure)
  .github/workflows/config/mlc_config.json
  .markdownlint.jsonc
  Document/0x04f-Testing-Network-Communication.md
  Document/0x05a-Platform-Overview.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x06a-Platform-Overview.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x08-Testing-Tools.md
  Document/Images/Chapters/0x05b/android_ssl_pinning_bypass.png
  Document/Images/Chapters/0x06b/ios_ssl_pinning_bypass.png
  Document/Images/Chapters/0x06g/manual-server-trust-evaluation.png
  Document/SUMMARY.md
  README.md
Labels: MASVS-NETWORK, tests

#2118 Improve the Android Architecture Section (by @NowSecure)
  .github/workflows/config/mlc_config.json
  Document/0x05a-Platform-Overview.md
Labels: Android

#2153 Add New References to Android API changes (by @NowSecure)
  Document/0x05a-Platform-Overview.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05h-Testing-Platform-Interaction.md
Labels: Android, fundamentals

#2156 New Chapter for Reference Apps #2142
  Document/0x02c-Acknowledgements.md
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05d-Testing-Data-Storage.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x05h-Testing-Platform-Interaction.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06f-Testing-Local-Authentication.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08a-Testing-Tools.md
  Document/0x08b-Reference-Apps.md
  Document/SUMMARY.md
  README.md
Labels: tools

#2161 Restrict labeler to opened PRs
  .github/workflows/labeler.yml
Labels: ignore-for-release

#2162 Fix some Crackme links
  Document/0x02c-Acknowledgements.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x08b-Reference-Apps.md
Labels: ignore-for-release

#2165 Fix docs broken pics
  docs/assets/comment-marked-as-answer.png
  docs/assets/hover-comment-icon.gif
  docs/assets/suggestion-block.png
  docs/contributing/1_How_Can_You_Contribute.md
  docs/contributing/2_Getting_Started.md
  docs/contributing/3_PRs_and_Reviews.md
  docs/index.md
  mkdocs.yml
Labels: ignore-for-release

#2166 Fix docs broken pics
  docs/contributing/1_How_Can_You_Contribute.md
  docs/contributing/2_Getting_Started.md
  docs/contributing/3_PRs_and_Reviews.md
Labels: ignore-for-release
