Repository OWASP/mastg, pull requests merged in 2022-10, with the labels that each got.

#2266 Add Crackmes Tab
  Crackmes/README.md
  Crackmes/iOS/Level_01/UnCrackable-Level1.ipa
  Crackmes/iOS/Level_02/UnCrackable-Level2.ipa
  Document/0x02c-Acknowledgements.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x08b-Reference-Apps.md
  README.md
  docs/Crackmes.md
  docs/crackmes/Android.md
  docs/crackmes/iOS.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: website

#2267 fix crackme links
  Crackmes/README.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08b-Reference-Apps.md
  README.md
Labels: ignore-for-release

#2268 fix file name
  mkdocs.yml
Labels: ignore-for-release

#2269 fix nav
  mkdocs.yml
Labels: ignore-for-release

#2270 Fix tab title
  mkdocs.yml
Labels: ignore-for-release

#2271 Fix case sensitive filename
  docs/crackmes.md
Labels: ignore-for-release

#2254 Add static analysis details for Android keyboard cache
  Document/0x05d-Testing-Data-Storage.md
Labels: Android, MASVS-STORAGE, tests

#2275 Update Talks (Cybersec Chile)
  docs/talks.md
Labels: news

#2280 Fix typo
  Document/0x04i-Testing-User-Privacy-Protection.md
Labels: ignore-for-release

#2279 Update 0x04f-Testing-Network-Communication.md
  Document/0x04f-Testing-Network-Communication.md
Labels: errata

#2282 Fix broken emoji links
  docs/contributing.md
Labels: ignore-for-release

#2284 Add Vulnerable App Example to 0x4h & 2 new Reference Apps
  Document/0x04h-Testing-Code-Quality.md
  Document/0x08b-Reference-Apps.md
Labels: tools, MASVS-CODE

#2288 Proofreading fixes 0x08b-Reference-Apps.md
  Document/0x08b-Reference-Apps.md
Labels: tools

#2289 Proofreading fixes part 1 0x05a-Platform-Overview.md
  Document/0x05a-Platform-Overview.md
Labels: Android, fundamentals, errata

#2292 Proofreading fixes 0x05a-Platform-Overview.md
  Document/0x05a-Platform-Overview.md
Labels: Android, fundamentals

#2293 Proofreading fixes 0x05b-Basic-Security_Testing.md
  Document/0x05b-Basic-Security_Testing.md
Labels: Android, fundamentals

#2298 Proofreading fixes part 3 5x05b Basic Security Testing
  Document/0x05b-Basic-Security_Testing.md
Labels: Android, fundamentals

#2299 Proofreading fixes - last part - 0x05b
  Document/0x05b-Basic-Security_Testing.md
Labels: Android, fundamentals

#2297 Proofreading fixes part 2 - Android basic security testing
  Document/0x05b-Basic-Security_Testing.md
Labels: Android, fundamentals

#2301 Proofreading fixes part 1 0x05c
  Document/0x05c-Reverse-Engineering-and-Tampering.md
Labels: Android, techniques

#2303 Add Guidelines to Contribute with Crackmes
  docs/contributing/6_Add_a_Crackme.md
Labels: org
