Repository OWASP/mastg, pull requests merged in 2022-06, with the labels that each got.

#2112 Issue #2111 - Add information on enabling Safari Web Inspector on iOS
  Document/0x06h-Testing-Platform-Interaction.md
Labels: iOS, MASVS-PLATFORM, techniques

#1938 0x04e - About OTP Authentication Checks
  Document/0x04e-Testing-Authentication-and-Session-Management.md
Labels: MASVS-AUTH, change-mstg

#2117 Fix corrupted picture
  Document/Images/Chapters/0x06a/code_signing.png
Labels: ignore-for-release

#2123 Fixed Typos in 0x04i-Testing-User-Privacy-Protection
  Document/0x04i-Testing-User-Privacy-Protection.md
Labels: errata

#2124 Update Corellium info and about decrypting IPAs
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06h-Testing-Platform-Interaction.md
Labels: iOS, techniques

#2125 Put Frontispiece before trusted by
  Document/0x02a-Frontispiece.md
Labels: ignore-for-release

#1915 Added instructions explaining how to move certificate from user to root store
  Document/0x05b-Basic-Security_Testing.md
Labels: fundamentals, change-mstg

#2051 Fix Intros in Cryptography Chapters (by @NowSecure)
  Document/0x05e-Testing-Cryptography.md
  Document/0x06e-Testing-Cryptography.md
Labels: errata

#1885 CRYPTO: Export and import crypto regulations
  Document/0x04g-Testing-Cryptography.md
Labels: MASVS-CRYPTO, change-mstg

#2130 Fix 0x04g outline
  Document/0x04g-Testing-Cryptography.md
Labels: MASVS-CRYPTO, ignore-for-release

#2090 0x05h - Enhance Android Deep Link Testing (by @NowSecure)
  Document/0x05a-Platform-Overview.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05h-Testing-Platform-Interaction.md
Labels: Android, MASVS-PLATFORM, tests

#2131 Upgrade codeql to v2 and OWASP logo white
  .github/workflows/codeql-analysis.yml
  Document/Images/OWASP_logo_white.png
Labels: ignore-for-release, automation
