Repository OWASP/mastg, pull requests merged in 2022-09, with the labels that each got.

#2196 fix spacing
  README.md
Labels: ignore-for-release

#2202 Fix Links and Add Transform Script from GitHub to Website
  .github/workflows/build-website.yml
  .gitignore
  docs/donate.md
  docs/index.md
  tools/scripts/transform_links.py
Labels: ignore-for-release

#2204 Fix link transform
  tools/scripts/transform_links.py
Labels: ignore-for-release

#2206 Fix donations page
  .github/ISSUE_TEMPLATE/make-donation.yml
  README.md
  docs/assets/OWASP_logo_white.png
  docs/assets/donations/mastg_donation_form.png
  docs/assets/donations/mstg_donation_form.png
  docs/assets/donations/owasp_donation_form.png
  docs/donate.md
  docs/index.md
  docs/news.md
Labels: ignore-for-release

#2207 Fix Release by Triggering docgen on Tag Push
  .github/workflows/docgenerator.yml
Labels: ignore-for-release

#2208 Add Common Test Case Column to Checklist and Other Pre-release Fixes
  CHANGELOG.md
  CITATION.cff
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Crackmes/README.md
  Document/0x01-Foreword.md
  Document/0x02a-Frontispiece.md
  Document/0x02b-MASVS-MASTG-Adoption.md
  Document/0x02c-Acknowledgements.md
  Document/0x03-Overview.md
  Document/0x04a-Mobile-App-Taxonomy.md
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x08a-Testing-Tools.md
  Document/CHANGELOG.md
  Document/Images/Chapters/0x03/mstg-detailed-summary.png
  Document/Images/Chapters/0x03/mstg-preparation.png
  Document/Images/Chapters/0x03/mstg-spiderchart.png
  Document/Images/Chapters/0x03/mstg-test-cases.png
  Document/Images/Chapters/0x03/owasp-mobile-overview.jpg
  Document/Images/Chapters/0x03/owasp-mobile-overview.png
  Document/Images/OWASP_logo.png
  Document/Images/OWASP_logo_white.png
  Document/Images/owasp_mas_header.png
  Document/SUMMARY.md
  OWASP_logo.png
  PULL_REQUEST_TEMPLATE.md
  README.md
  docs/contributing/5_Style_Guide.md
  docs/news.md
  tools/docker/first_page.tex
  tools/docker/pandoc_makedocs.sh
  tools/scripts/excel_styles_and_validation.py
  tools/scripts/gen_all_excel.sh
  tools/scripts/testcase_diff.py
  tools/scripts/yaml_to_excel.py
Labels: checklists

#2227 fix frontispiece links
  Document/0x02a-Frontispiece.md
Labels: ignore-for-release

#2231 Pdffixes
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Labels: ignore-for-release

#2232 Remove Appendix and N/A from Checklists
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x04g-Testing-Cryptography.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06f-Testing-Local-Authentication.md
  Document/0x07-Appendix.md
  tools/scripts/yaml_to_excel.py
Labels: ignore-for-release

#2233 Fix Reference Links for PDF
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x04i-Testing-User-Privacy-Protection.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05f-Testing-Local-Authentication.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06e-Testing-Cryptography.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08a-Testing-Tools.md
  docs/contributing/5_Style_Guide.md
Labels: ignore-for-release

#2234 Enhance Auto Release Notes
  .github/release.yml
Labels: automation

#2235 Add MASVS version to MASTG PDF
  .github/workflows/docgenerator.yml
  Document/0x02c-Acknowledgements.md
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x04f-Testing-Network-Communication.md
  Document/0x04g-Testing-Cryptography.md
  Document/0x04i-Testing-User-Privacy-Protection.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05f-Testing-Local-Authentication.md
  Document/0x05g-Testing-Network-Communication.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06e-Testing-Cryptography.md
  Document/0x06h-Testing-Platform-Interaction.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08a-Testing-Tools.md
  cover.png
  docs/contributing/5_Style_Guide.md
  tools/docker/cover.tex
  tools/docker/first_page.tex
  tools/docker/pandoc_makedocs.sh
Labels: automation

#2236 Fix ns logo and ada masa pic
  Document/0x02c-Acknowledgements.md
  Document/Images/Chapters/0x04i/masa_framework.png
Labels: ignore-for-release

#2237 Update covers and read links
  docs/assets/mastg_cover.png
  docs/assets/masvs_cover.png
  docs/donate.md
  docs/index.md
  tools/README.md
  tools/updateLeanpub.sh
Labels: ignore-for-release

#2240 Upgrade icons, talks and index page
  docs/assets/checklist_en_filled.png
  docs/donate.md
  docs/index.md
  docs/news.md
  docs/talks.md
  mkdocs.yml
Labels: ignore-for-release

#2241 Add contact page
  .github/workflows/config/mlc_config.json
  docs/assets/carlos.jpg
  docs/assets/sven.jpg
  docs/contact.md
  docs/index.md
Labels: ignore-for-release

#2243 fix sed commands
  .github/workflows/build-website.yml
Labels: ignore-for-release

#2245 Fix masvs lang to EN and other minor fixes
  docs/contributing.md
  mkdocs.yml
  tools/scripts/structure_masvs.sh
Labels: ignore-for-release

#2246 Fix Index Page Layout & add OWASP (R)
  docs/index.md
  docs/stylesheets/extra.css
  docs/talks.md
  mkdocs.yml
Labels: ignore-for-release

#2248 fix links
  Document/0x02c-Acknowledgements.md
  docs/MASTG.md
Labels: ignore-for-release

#2249 fix broken links
  docs/contributing.md
  docs/donate.md
  docs/index.md
Labels: ignore-for-release

#2253 Fix transform script to set correct links
  .github/workflows/build-website.yml
  mkdocs.yml
  tools/scripts/structure_mastg.sh
  tools/scripts/transform_files.py
Labels: ignore-for-release

#2255 Fix typo
  Document/0x05d-Testing-Data-Storage.md
Labels: errata

#2257 Add MASVS refactor info & button
  docs/MASVS.md
  docs/index.md
Labels: ignore-for-release
