Repository OWASP/mastg, pull requests merged in 2022-11, with the labels that each got.

#2286 [Phase 1] Refactor 0x05h-Testing-Platform-Interaction.md (@NowSecure)
  Document/0x05h-Testing-Platform-Interaction.md
Labels: Android, MASVS-PLATFORM, tests

#2304 Proofreading fixes part 2 0x05c
  Document/0x05c-Reverse-Engineering-and-Tampering.md
Labels: Android, techniques

#2321 [Phase 1] Refactor 0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08a-Testing-Tools.md
Labels: iOS, MASVS-RESILIENCE, tests

#2327 Proofreading fixes part 3 0x05c
  Document/0x05c-Reverse-Engineering-and-Tampering.md
Labels: Android, techniques

#2330 Proofreading fixes part 4 0x05c
  Document/0x05c-Reverse-Engineering-and-Tampering.md
Labels: Android, techniques
