Repository OWASP/mastg, pull requests merged in 2022-08, with the labels that each got.

#2171 Update talks.md
  docs/talks.md
Labels: ignore-for-release

#2175 Fix CREST logo
  Document/0x02b-MASVS-MSTG-Adoption.md
Labels: ignore-for-release

#2176 Fix CREST logo
  Document/0x02b-MASVS-MSTG-Adoption.md
Labels: ignore-for-release

#2167 Update emulation available on iOS
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Labels: iOS, MASVS-RESILIENCE, tests

#2177 add new testing tool APKLab
  .github/ISSUE_TEMPLATE/make-donation.yml
  .github/workflows/spell-checker.yml
  Document/0x04i-Testing-User-Privacy-Protection.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x08a-Testing-Tools.md
Labels: Android, tools, techniques

#2178 Fix typo in 0x04f-Testing-Network-Communication.md
  Document/0x04f-Testing-Network-Communication.md
Labels: errata

#2181 Add new covers
  Document/Images/masvs_refactor.png
  docs/assets/mastg_cover.png
  docs/assets/masvs_cover.png
  docs/assets/mstg_cover.png
  docs/index.md
Labels: ignore-for-release

#2182 Add analytics
  mkdocs.yml
Labels: ignore-for-release

#2185 Add CNAME
  docs/CNAME
Labels: ignore-for-release

#2187 Add MAS advocate to website
  docs/index.md
Labels: ignore-for-release

#2191 Minor fix
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
Labels: ignore-for-release

#2192 fix logo and links
  docs/contributing/1_How_Can_You_Contribute.md
  docs/index.md
Labels: ignore-for-release

#2193 Fix link check error & move Contribution Credit section
  .github/workflows/config/mlc_config.json
  README.md
  docs/contributing/1_How_Can_You_Contribute.md
  docs/donate.md
  docs/index.md
Labels: ignore-for-release

#2194 fix logos
  docs/index.md
Labels: ignore-for-release
