Repository OWASP/mastg, pull requests merged in 2022-01, with the labels that each got.

#2027 Update oauth RFC links
  Document/0x04e-Testing-Authentication-and-Session-Management.md
Labels: MASVS-AUTH, ignore-for-release

#2030 Remove title from link
  Document/0x04a-Mobile-App-Taxonomy.md
Labels: ignore-for-release

#2031 add vscode settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: ignore-for-release

#2028 Fix all logos
  Document/0x02-Frontispiece.md
  Document/Images/Donators/NowSecure_logo.png
  Document/Images/Donators/Randorisec_logo.png
  Document/Images/Donators/SEC_Consult_logo.png
  Document/Images/Donators/ZIMPERIUM_logo.png
  Document/Images/Donators/donators.png
Labels: org, ignore-for-release

#2010 Automated Checklist and YAML Generation
  .github/workflows/docexport.yml
  Document/Images/logo_circle.png
  tools/scripts/excel_styles_and_validation.py
  tools/scripts/gen_all_excel.sh
  tools/scripts/mstg_to_html.sh
  tools/scripts/parse_html.py
  tools/scripts/requirements.txt
  tools/scripts/yaml_to_excel.py
Labels: org

#2033 Merge workflows
  .github/workflows/docexport.yml
  .github/workflows/docgenerator.yml
Labels: org, ignore-for-release

#2034 Fix conditional formatting and get latest tag
  .github/workflows/docgenerator.yml
  tools/scripts/excel_styles_and_validation.py
  tools/scripts/gen_all_excel.sh
  tools/scripts/yaml_to_excel.py
Labels: ignore-for-release

#2035 Update to MSTG Blue
  .vscode/settings.json
  Checklists/Mobile_App_Security_Checklist-English_1.2.xlsx
  Checklists/Mobile_App_Security_Checklist-French_1.2.xlsx
  Checklists/Mobile_App_Security_Checklist-Japanese_1.2.xlsx
  Checklists/Mobile_App_Security_Checklist-Korean_1.2.xlsx
  Checklists/Mobile_App_Security_Checklist-Spanish_1.2.xlsx
  Checklists/README.md
  Checklists/checklinks.py
  Document/Images/logo_circle.png
  README.md
  tools/scripts/excel_styles_and_validation.py
  tools/scripts/yaml_to_excel.py
Labels: ignore-for-release

#2025 Add link to latest code signature format
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Labels: iOS, MASVS-CODE

#1992 Fixing typos and more in the Android Crypto Chapter
  Document/0x05e-Testing-Cryptography.md
Labels: MASVS-CRYPTO

#2041 Add damnvulnerableiosapp.com to exception list for link checker
  .github/workflows/config/mlc_config.json
Labels: ignore-for-release

#1943 0x06b - Upgrade Jailbreak section
  Document/0x06b-Basic-Security-Testing.md
Labels: Fundamentals, change-mstg

#1964 Vendor Neutrality Assurance
  Document/0x02-Frontispiece.md
  Document/0x05b-Basic-Security_Testing.md
  Document/0x05f-Testing-Local-Authentication.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06g-Testing-Network-Communication.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x08-Testing-Tools.md
  Users.md
Labels: org, ignore-for-release

#2043 Fix donators panel
  Document/Images/Donators/donators.png
Labels: ignore-for-release
