Repository OWASP/mastg, pull requests merged in 2022-02, with the labels that each got.

#2057 Update Changelog Automation
  .github/release.yml
Labels: automation

#2061 Improve README UX
  .markdownlint.json
  Document/Images/GitHub_logo.png
  Document/Images/slack_logo.png
  Document/Images/twitter_logo.png
  README.md
Labels: org

#2064 Show MASVS Refactoring Button
  Document/Images/masvs_refactor.png
  README.md
Labels: ignore-for-release

#2067 Fix typos discovered by codespell
  CONTRIBUTING.md
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x05c-Reverse-Engineering-and-Tampering.md
  Document/0x05d-Testing-Data-Storage.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05h-Testing-Platform-Interaction.md
  Document/0x06b-Basic-Security-Testing.md
  Document/0x06c-Reverse-Engineering-and-Tampering.md
  Document/0x06d-Testing-Data-Storage.md
  Document/0x06h-Testing-Platform-Interaction.md
  README.md
  style_guide.md
  tools/README.md
Labels: errata
