Repository OWASP/mastg, pull requests merged in 2023-05, with the labels that each got.

#2406 Fix release step for uploading artifacts
  .github/workflows/docgenerator.yml
Labels: ignore-for-release

#2409 Update README.md
  README.md
Labels: ignore-for-release

#2411 Fix typo MASVS.md
  docs/MASVS.md
Labels: ignore-for-release

#2414 Proofreading fixes 0x05d part 4
  Document/0x05d-Testing-Data-Storage.md
Labels: Android, MASVS-STORAGE, tests

#2419 Fix status validation for MASVS controls in checklist
  tools/scripts/yaml_to_excel.py
Labels: ignore-for-release

#2416 [ios_0x06d/0055] Fix the description of the keyboard cache location
  Document/0x06d-Testing-Data-Storage.md
  tests/ios/MASVS-STORAGE/MASTG-TEST-0055.md
Labels: iOS, MASVS-STORAGE, tests
