Repository OWASP/mastg, pull requests merged in 2023-09, with the labels that each got.

#2436 Add news about the MAS Score Formula Proposal
  docs/assets/news/mas_formula_paper.png
  docs/news.md
Labels: news

#2440 Add Zimperium to God Mode Donators
  Document/Images/Donators/donators.png
Labels: donation

#2449 Fix checklist link
  docs/index.md
Labels: ignore-for-release
