Repository OWASP/mastg, pull requests merged in 2024-08, with the labels that each got.

#2859 Fix CWE ids to be just numbers
  weaknesses/MASVS-NETWORK/MASWE-0050.md
  weaknesses/MASVS-NETWORK/MASWE-0052.md
Labels: ignore-for-release

#2861 update donators
  Document/Images/Donators/donators.png
Labels: ignore-for-release

#2862 Remove toc from apps and tools and add new MASTG buttons
  Document/0x08a-Testing-Tools.md
  Document/0x08b-Reference-Apps.md
  Document/index.md
  tools/index.md
Labels: tools, ignore-for-release

#2867 Update MASWE-0040.md with new links
  weaknesses/MASVS-AUTH/MASWE-0040.md
Labels: ignore-for-release

#2868 [MASTG-TOOL-0109] Add Nope proxy (by @appknox)
  tools/network/MASTG-TOOL-0109.md
Labels: tools

#2877 Fix news not showing
  docs/news/index.md
  mkdocs.yml
Labels: ignore-for-release

#2878 Update MASWE-0100 refs
  weaknesses/MASVS-RESILIENCE/MASWE-0100.md
Labels: ignore-for-release

#2883 Update talks.yaml
  docs/assets/data/talks.yaml
Labels: ignore-for-release

#2885 fix rule file name
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0012/run.sh
  rules/mastg-android-weak-key-generation.yml
Labels: ignore-for-release

#2886 Update MASTG-DEMO-0012.md rule name
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0012/MASTG-DEMO-0012.md
Labels: ignore-for-release

#2888 Fix title for MASTG-DEMO-0011.md
  demos/ios/MASVS-CRYPTO/MASTG-DEMO-0011/MASTG-DEMO-0011.md
Labels: ignore-for-release
