Repository OWASP/mastg, pull requests merged in 2024-02, with the labels that each got.

#2522 Show MASVS v1 IDs in the tests teables
  src/scripts/populate_dynamic_pages.py
Labels: ignore-for-release

#2371 Replace safetyNey to Play Integrity
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
Labels: Android, MASVS-RESILIENCE, tests

#2463 Proofreading fixes 0x04i Testing-User-Privacy-Protection.md
  Document/0x04i-Testing-User-Privacy-Protection.md
Labels: MASVS-PRIVACY, fundamentals

#2564 Set depth to 0 & add last updated to the tests table
  .github/workflows/build-website.yml
  src/scripts/populate_dynamic_pages.py
Labels: ignore-for-release
