Repository OWASP/mastg, pull requests merged in 2024-11, with the labels that each got.

#2927 fix android mappings
  weaknesses/MASVS-CRYPTO/MASWE-0009.md
  weaknesses/MASVS-CRYPTO/MASWE-0014.md
  weaknesses/MASVS-CRYPTO/MASWE-0027.md
  weaknesses/MASVS-NETWORK/MASWE-0052.md
  weaknesses/MASVS-STORAGE/MASWE-0001.md
  weaknesses/MASVS-STORAGE/MASWE-0002.md
  weaknesses/MASVS-STORAGE/MASWE-0005.md
  weaknesses/MASVS-STORAGE/MASWE-0006.md
  weaknesses/MASVS-STORAGE/MASWE-0007.md
Labels: ignore-for-release

#3022 fix display of deprecated
  docs/hooks/create_dynamic_tables.py
Labels: ignore-for-release

#3027 Port mastg test 0020 (by @guardsquare)
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0217.md
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0218.md
  tests/android/MASVS-NETWORK/MASTG-TEST-0020.md
Labels: MASTG Refactor, changes-requested

#3029 Port MASTG-TEST-0083 (by @guardsquare)
  techniques/ios/MASTG-TECH-0113.md
  techniques/ios/MASTG-TECH-0114.md
  tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0219.md
  tests/ios/MASVS-RESILIENCE/MASTG-TEST-0083.md
  tools/ios/MASTG-TOOL-0121.md
  tools/ios/MASTG-TOOL-0122.md
Labels: MASTG Refactor

#3050 Update MASWE-0002.md
  weaknesses/MASVS-STORAGE/MASWE-0002.md
Labels: ignore-for-release

#2881 blutter tool added (by @appknox)
  tools/android/MASTG-TOOL-0116.md
Labels: tools, changes-requested

#3057 Update MASWE-0116.md
  weaknesses/MASVS-CODE/MASWE-0116.md
Labels: ignore-for-release

#3060 Update MASWE-0002.md
  weaknesses/MASVS-STORAGE/MASWE-0002.md
Labels: ignore-for-release

#3044 Port MASTG test 0038 (by @guardsquare)
  Document/0x05a-Platform-Overview.md
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  techniques/android/MASTG-TECH-0116.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x38-2.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0x38.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0038.md
  tools/android/MASTG-TOOL-0123.md
Labels: Android, fundamentals, changes-requested

#3065 Update MASTG-DEMO-0019.md
  demos/ios/MASVS-STORAGE/MASTG-DEMO-0019/MASTG-DEMO-0019.md
Labels: ignore-for-release

#3066 Update isExcludedFromBackup.r2
  demos/ios/MASVS-STORAGE/MASTG-DEMO-0019/isExcludedFromBackup.r2
Labels: ignore-for-release

#3071 Fix images paths in Update structure_masvs.sh
  src/scripts/structure_masvs.sh
Labels: ignore-for-release

#3042 Port MASTG test 0039 (by @guardsquare)
  techniques/android/MASTG-TECH-0117.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0226.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0227.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0039.md
  tools/android/MASTG-TOOL-0124.md
Labels: MASTG Refactor

#3056 Port MASTG test 0087 (by @guardsquare)
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  techniques/android/MASTG-TECH-0115.md
  techniques/ios/MASTG-TECH-0082.md
  techniques/ios/MASTG-TECH-0118.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-1.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-2.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-3.md
  tests/ios/MASVS-CODE/MASTG-TEST-0087.md
Labels: iOS, MASVS-CODE, almost-ready

#3075 fix IDs
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0228.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0229.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0230.md
Labels: ignore-for-release

#3059 Port MASTG-TEST-0003 (by @guardsquare)
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0203.md
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0231.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0003.md
Labels: MASTG Refactor, almost-ready
