Repository OWASP/mastg, pull requests merged in 2024-05, with the labels that each got.

#2611 Remove link processing temporarily & fix md links
  src/scripts/transform_files.py
  techniques/android/MASTG-TECH-0017.md
  techniques/android/MASTG-TECH-0023.md
  techniques/android/MASTG-TECH-0026.md
  techniques/android/MASTG-TECH-0031.md
  techniques/android/MASTG-TECH-0040.md
  techniques/android/MASTG-TECH-0043.md
  techniques/android/MASTG-TECH-0100.md
  techniques/android/MASTG-TECH-0108.md
  techniques/ios/MASTG-TECH-0053.md
  techniques/ios/MASTG-TECH-0057.md
  techniques/ios/MASTG-TECH-0058.md
  techniques/ios/MASTG-TECH-0059.md
  techniques/ios/MASTG-TECH-0061.md
  techniques/ios/MASTG-TECH-0076.md
  techniques/ios/MASTG-TECH-0079.md
  techniques/ios/MASTG-TECH-0084.md
  techniques/ios/MASTG-TECH-0088.md
  techniques/ios/MASTG-TECH-0089.md
  techniques/ios/MASTG-TECH-0090.md
  techniques/ios/MASTG-TECH-0092.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0013.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0046.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0047.md
  tests/ios/MASVS-RESILIENCE/MASTG-TEST-0081.md
  tests/ios/MASVS-RESILIENCE/MASTG-TEST-0082.md
  tools/android/MASTG-TOOL-0001.md
Labels: ignore-for-release

#2570 Updated Decrypting Realm Databases in 0x05d - Testing Data Storage and 0x06d-Testing-Data-Storage
  Document/0x05d-Testing-Data-Storage.md
  Document/0x06d-Testing-Data-Storage.md
Labels: Android, MASVS-STORAGE, changes-requested

#2615 Rename examples to demos
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/common-use-of-random.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/demo.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.sarif
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.txt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/run.sh
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/demo.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/non-random.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.sarif
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.txt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/run.sh
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/demo.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/mitm_sensitive_logger.py
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/run.sh
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/send-post-request.kt
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/sensitive_data.log
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/demo.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/logcat_output.txt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/output.txt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/run.sh
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/snippet.kt
Labels: ignore-for-release

#2616 Fix broken links to 0x05|6c-Reverse-Engineering-and-Tampering.md
  .github/workflows/config/url-checker-config.json
  Document/0x04c-Tampering-and-Reverse-Engineering.md
  Document/0x05e-Testing-Cryptography.md
  Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/0x06b-iOS-Security-Testing.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
  Document/SUMMARY.md
  techniques/android/MASTG-TECH-0004.md
  techniques/android/MASTG-TECH-0011.md
  techniques/generic/MASTG-TECH-0048.md
  techniques/ios/MASTG-TECH-0055.md
  techniques/ios/MASTG-TECH-0087.md
  techniques/ios/MASTG-TECH-0089.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0013.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0014.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0015.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0016.md
  tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0051.md
  tests/ios/MASVS-PLATFORM/MASTG-TEST-0059.md
  tests/ios/MASVS-RESILIENCE/MASTG-TEST-0090.md
  tests/ios/MASVS-STORAGE/MASTG-TEST-0060.md
  tools/android/MASTG-TOOL-0001.md
  tools/android/MASTG-TOOL-0012.md
  tools/android/MASTG-TOOL-0030.md
Labels: errata

#2617 Update Existing Demos to use MASTestApp and reversed code
  .gitignore
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/MastgTest.kt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/MastgTest_reversed.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/common-use-of-random.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.sarif
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.txt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/run.sh
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/MastgTest.kt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/MastgTest_reversed.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/non-random.java
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.sarif
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.txt
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/run.sh
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/MastgTest.kt
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/send-post-request.kt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/MastgTest.kt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/logcat_output.txt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/output.txt
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/run.sh
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/snippet.kt
Labels: ignore-for-release
