Repository OWASP/mastg, pull requests merged in 2024-07, with the labels that each got.

#2656 Fix datatables style
  Document/0x05h-Testing-Platform-Interaction.md
  docs/hooks/add-tags.py
  docs/index.md
  docs/javascripts/datatables.js
  docs/stylesheets/extra.css
Labels: ignore-for-release

#2565 [MASWE-0005] Add Sensitive Data Hardcoded in the App Package
  weaknesses/MASVS-STORAGE/MASWE-0005.md
Labels: changes-requested

#2566 [MASWE-0006] Add Sensitive Data Stored Unencrypted in Private Storage Locations
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/MASTG-DEMO-0010.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/new_files/secret.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/run_after.sh
  demos/android/MASVS-STORAGE/MASTG-DEMO-0010/run_before.sh
  tests/android/MASVS-STORAGE/MASTG-TEST-0207.md
  weaknesses/MASVS-STORAGE/MASWE-0006.md
Labels: MASWE

#2784 Remove 'About Hybrid Apps' from README
  README.md
Labels: ignore-for-release

#2789 restore link to news
  docs/news/.authors.yml
  docs/news/index.md
  docs/news/posts/2016-12-04-call-for-authors-the-ultimate-open-source-mobile-app-reverse-engineering-guide.md
  docs/news/posts/2017-01-22-mobile-testing-guide-toc-available.md
  docs/news/posts/2017-01-28-mobile-crackmes-and-reversing-tutorials.md
  docs/news/posts/2017-01-31-mobile-app-security-verification-standard-v0-9-2-available-for-download.md
  docs/news/posts/2017-04-05-mobile-app-security-verification-standard-update.md
  docs/news/posts/2017-06-05-mobile-security-testing-workshop-on-the-owasp-summit-2017.md
  docs/news/posts/2017-06-17-the-owasp-mobile-security-testing-guide-summit-preview.md
  docs/news/posts/2017-07-05-sponsorship-packages-announced.md
  docs/news/posts/2017-09-14-mobile-app-security-verification-standard-update.md
  docs/news/posts/2018-01-13-mobile-app-security-verification-standard-release-1-0.md
  docs/news/posts/2018-06-15-mobile-security-testing-guide-release-1-0.md
  docs/news/posts/2018-06-16-jeroen-willemsen-joins-as-project-lead.md
  docs/news/posts/2018-08-02-mobile-app-security-verification-standard-releases.md
  docs/news/posts/2018-09-01-mobile-security-testing-guide-mentioned-in-nist-sp-163r1.md
  docs/news/posts/2018-09-16-mstg-1-0-1-released.md
  docs/news/posts/2018-09-21-masvs-automation-started.md
  docs/news/posts/2018-10-13-mstg-1-0-2-released-twitter-account.md
  docs/news/posts/2018-10-18-the-mstg-is-now-officially-an-owasp-lab-project.md
  docs/news/posts/2018-10-28-call-for-company-references.md
  docs/news/posts/2018-10-28-the-masvs-is-getting-more-translations.md
  docs/news/posts/2018-11-30-release-1-1-0-of-the-mstg.md
  docs/news/posts/2019-01-03-multilanguage-release-1-1-2-of-the-masvs.md
  docs/news/posts/2019-01-15-release-of-improved-checklist.md
  docs/news/posts/2019-04-15-book-version-project-promotion-preparation-for-the-summit.md
  docs/news/posts/2019-05-07-new-release-of-the-mstg.md
  docs/news/posts/2019-05-21-new-release-of-the-mstg.md
  docs/news/posts/2019-06-05-new-release-of-the-masvs.md
  docs/news/posts/2019-08-02-project-promoted-to-flagship-status.md
  docs/news/posts/2019-08-04-oss-release.md
  docs/news/posts/2019-08-29-carlos-holguera-joins-the-leader-team.md
  docs/news/posts/2019-09-06-flutter-experiment.md
  docs/news/posts/2019-09-06-react-native-experiment.md
  docs/news/posts/2019-09-17-xamarin-experiment.md
  docs/news/posts/2019-10-02-mstg-playground-release.md
  docs/news/posts/2019-10-02-mstg-project-joins-hacktoberfest.md
  docs/news/posts/2019-10-04-pre-release-of-masvs-1-2.md
  docs/news/posts/2020-03-17-international-release-of-masvs-1-2.md
  docs/news/posts/2020-04-10-stayhome-and-share-your-knowledge.md
  docs/news/posts/2020-05-23-new-build-system-and-release-upcoming.md
  docs/news/posts/2021-11-17-from-slack-to-github-discussions.md
  docs/news/posts/2022-02-07-nist-800-218.md
  docs/news/posts/2022-08-23-project-rebranding-to-owasp-mas.md
  docs/news/posts/2023-04-01-masvs-v2-0-0-release.md
  docs/news/posts/2023-05-08-masvs-v2-colors.md
  docs/news/posts/2023-07-28-mas-testing-profiles-and-mastg-atomic-tests.md
  docs/news/posts/2023-09-20-request-for-community-review.md
  docs/news/posts/2023-09-29-mastg-refactor-part-2.md
  docs/news/posts/2023-10-10-masvs-privacy.md
  docs/news/posts/2024-01-11-mobile-application-risk-scoring-qa.md
  docs/news/posts/2024-01-18-masvs-v2-1-0-release.md
  docs/news/posts/2024-02-19-new-standard-for-secure-mobile-app-transactions.md
  mkdocs.yml
Labels: ignore-for-release

#2791 Add cross-references hook
  mkdocs.yml
Labels: ignore-for-release

#2807 Fix GitHub build?
  .github/workflows/docgenerator.yml
  src/scripts/structure_masvs.sh
Labels: ignore-for-release

#2782 [MASTG-TOOL-0103] add uber-apk-signer
  tools/android/MASTG-TOOL-0103.md
Labels: Android, tools

#2798 [TOOL] Adding hermes-dec as a general tool for React Native static analysis
  tools/generic/MASTG-TOOL-0104.md
Labels: tools

#2831 fix secr3tPa$$W0rd string
  demos/android/MASVS-STORAGE/MASTG-DEMO-0001/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0004/MastgTest.kt
Labels: ignore-for-release

#2835 Update packages.md
  docs/donate/packages.md
Labels: ignore-for-release

#2840 [MASTG-DEMO-0002] Fix Frida script ContentResolver.insert overload
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/script.js
Labels: demos

#2843 Limit demos action to changes in demos folder
  .github/workflows/build-android-demos.yml
Labels: ignore-for-release

#2614 [MASTG-TOOL-0015] Update drozer content and remove outdated references
  tools/android/MASTG-TOOL-0015.md
Labels: tools

#2845 Add new talk at OWASP Atlanta Chapter
  docs/assets/data/talks.yaml
Labels: news

#2846 Add new blog post
  docs/assets/news/MASTG-DEMO-0002-studio.png
  docs/assets/news/MASTG-DEMO-0002-vscode.png
  docs/assets/news/MASTG-DEMO-0002-web.png
  docs/assets/news/apk_build_autom.png
  docs/assets/news/app_automation_vision.png
  docs/assets/news/mas_v2_arch.png
  docs/assets/news/mastestapps.png
  docs/assets/news/mastg_v2_structure.png
  docs/assets/news/maswe_main.png
  docs/news/posts/2024-07-30-new-maswe.md
Labels: news

#2851 Add news error banner
  docs/news/index.md
Labels: ignore-for-release
