Repository OWASP/mastg, pull requests merged in 2024-06, with the labels that each got.

#2629 Update 4_Add_new_Language.md
  docs/contributing/4_Add_new_Language.md
Labels: ignore-for-release

#2630 Update the list of permissions (up to API level 34) into the risk…
  Document/0x05h-Testing-Platform-Interaction.md
Labels: Android, MASVS-PLATFORM

#2632 Enable snippets and tabs
  .gitignore
  docs/hooks/replace_snippets.py
  docs/hooks/update_titles.py
  mkdocs.yml
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/demo.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/demo.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/demo.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/demo.md
  run_web.sh
  src/scripts/structure_mastg.sh
Labels: ignore-for-release

#2633 Fix mappings, fix consistency in test and risk sections
  Document/0x04b-Mobile-App-Security-Testing.md
  mkdocs.yml
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/test.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/test.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/risk.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/MastgTest.kt
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/MastgTest_reversed.java
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/demo.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/test.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/risk.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/test.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/risk.md
  src/scripts/populate_dynamic_pages.py
Labels: ignore-for-release

#2634 Fix broken links
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/test.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/test.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/test.md
Labels: ignore-for-release

#2635 fix md links to tools and tech
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/test.md
  risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/test.md
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/test.md
  risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/test.md
Labels: ignore-for-release

#2636 fix md links to tools and tech
  risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/test.md
Labels: ignore-for-release

#2638 Add MASWE Index and rename to weakness
  mkdocs.yml
  src/scripts/populate_dynamic_pages.py
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/MastgTest.kt
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/MastgTest_reversed.java
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/demo.md
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.sarif
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/output.txt
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/run.sh
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/rules/mastg-android-insecure-random-use.yaml
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/test.md
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/MastgTest.kt
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/MastgTest_reversed.java
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/demo.md
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.sarif
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/output.txt
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/run.sh
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/rules/mastg-android-non-random-use.yaml
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/test.md
  weaknesses/MASVS-CRYPTO/1-strong-crypto/insecure-random/weakness.md
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/MastgTest.kt
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/MastgTest_reversed.java
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/demo.md
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/mitm_sensitive_logger.py
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/run.sh
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/sensitive_data.log
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/test.md
  weaknesses/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/weakness.md
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/MastgTest.kt
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/demo.md
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/logcat_output.txt
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/output.txt
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/run.sh
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/test.md
  weaknesses/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/weakness.md
  weaknesses/index.md
Labels: ignore-for-release

#2639 Update structure_mastg.sh
  src/scripts/structure_mastg.sh
Labels: ignore-for-release

#2640 Update structure_mastg.sh
  src/scripts/structure_mastg.sh
Labels: ignore-for-release

#2641 Update structure_mastg.sh
  docs/hooks/update_titles.py
  src/scripts/structure_mastg.sh
Labels: ignore-for-release

#2600 Added ios & android technique and tool for re-flutter (by @appknox)
  apps/android/MASTG-APP-0017.md
  apps/ios/MASTG-APP-0027.md
  techniques/android/MASTG-TECH-0109.md
  techniques/ios/MASTG-TECH-0110.md
  tools/generic/MASTG-TOOL-0100.md
  tools/generic/MASTG-TOOL-0101.md
Labels: changes-requested

#2642 Update nav with MASWE Beta
  mkdocs.yml
Labels: ignore-for-release

#2643 add img and mas apps info
  docs/assets/maswe-overview.png
  weaknesses/index.md
Labels: ignore-for-release

#2644 Add MASWE Beta banner
  docs/hooks/maswe-beta-banner.py
  mkdocs.yml
  weaknesses/index.md
Labels: ignore-for-release

#2645 Update MASVS cover and populate MASVS control tables
  .github/workflows/build-website.yml
  docs/assets/masvs_cover.png
  src/scripts/structure_mastg.sh
Labels: ignore-for-release

#2646 fix call to script
  .github/workflows/build-website.yml
Labels: ignore-for-release
