Repository OWASP/mastg, pull requests merged in 2025-04, with the labels that each got.

#3251 MASWE-0069 draft: Add android risk reference for WebViews local resource access
  weaknesses/MASVS-PLATFORM/MASWE-0069.md
Labels: ignore-for-release

#3201 Enhance logging for external storage access in MASTG-DEMO-0002
  .github/workflows/spell-checker-pr.yml
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/MASTG-DEMO-0002.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0002/script.js
Labels: ready-for-review

#3244 [MASWE-0067] New MASWE Debuggable Flag Not Disabled and MASTG-DEMO-0040 (by @appknox)
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0040/AndroidManifest.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0040/AndroidManifest_reversed.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0040/MASTG-DEMO-0040.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0040/output.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0040/run.sh
  rules/mastg-android-debuggable-flag.yml
  weaknesses/MASVS-PLATFORM/MASWE-0067.md
Labels: almost-ready

#3260 Fix naming error (password.txt to sensitive_info.txt)
  Document/0x05d-Testing-Data-Storage.md
Labels: Android, MASVS-STORAGE
