Repository OWASP/mastg, pull requests merged in 2025-07, with the labels that each got.

#3367 Update .gitignore to exclude references.json
  .gitignore
Labels: ignore-for-release

#3377 remove redundant comments
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0012/MastgTest.kt
Labels: ignore-for-release

#3376 Update FUNDING.yml
  .github/FUNDING.yml
Labels: ignore-for-release

#3149 Update CWE mapping on MASWE elements of MASVS-PLATFORM
  weaknesses/MASVS-PLATFORM/MASWE-0058.md
  weaknesses/MASVS-PLATFORM/MASWE-0059.md
  weaknesses/MASVS-PLATFORM/MASWE-0060.md
  weaknesses/MASVS-PLATFORM/MASWE-0061.md
  weaknesses/MASVS-PLATFORM/MASWE-0062.md
  weaknesses/MASVS-PLATFORM/MASWE-0063.md
  weaknesses/MASVS-PLATFORM/MASWE-0064.md
  weaknesses/MASVS-PLATFORM/MASWE-0065.md
  weaknesses/MASVS-PLATFORM/MASWE-0066.md
  weaknesses/MASVS-PLATFORM/MASWE-0067.md
  weaknesses/MASVS-PLATFORM/MASWE-0068.md
  weaknesses/MASVS-PLATFORM/MASWE-0069.md
  weaknesses/MASVS-PLATFORM/MASWE-0070.md
  weaknesses/MASVS-PLATFORM/MASWE-0071.md
  weaknesses/MASVS-PLATFORM/MASWE-0072.md
  weaknesses/MASVS-PLATFORM/MASWE-0073.md
  weaknesses/MASVS-PLATFORM/MASWE-0074.md
Labels: MASWE

#3368 Fix metadata gathering and path handling in hooks
  docs/hooks/add-cross-references.py
  docs/hooks/extract-id-from-path.py
  docs/hooks/replace_snippets.py
Labels: ignore-for-release

#3397 Update README to align with other repos and Improve Contribution Docs
  README.md
  docs/contributing/1_How_Can_You_Contribute.md
  docs/contributing/2_Getting_Started.md
  docs/contributing/3_PRs_and_Reviews.md
  docs/contributing/5_Style_Guide.md
  docs/contributing/7_Run_the_Website.md
Labels: org, ignore-for-release

#3400 Convert structure_maswe script to a hook
  .github/workflows/build-website-reusable.yml
  .vscode/tasks.json
  Document/0x02a-Frontispiece.md
  docs/hooks/add-tags.py
  docs/hooks/add_redirects.py
  docs/hooks/combine-repos.py
  docs/hooks/create_dynamic_tables.py
  docs/hooks/fix-serve-watch.py
  docs/hooks/resolve_references.py
  docs/hooks/structure-mastg.py
  docs/hooks/structure-masvs.py
  mkdocs.yml
  run_web.sh
  src/scripts/structure_maswe.sh
Labels: website

#3408 Correct placeholder test and demo location
  demos/android/MASVS-STORAGE/MASTG-DEMO-0060/MASTG-DEMO-0060.md
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0287.md
Labels: ignore-for-release

#3411 Fix small typo in 0x02c-Acknowledgements.md
  Document/0x02c-Acknowledgements.md
Labels: ignore-for-release

#3412 Update .gitignore to ignore docs/MASVS
  .gitignore
Labels: ignore-for-release

#3415 Update 0x04b-Mobile-App-Security-Testing.md to remove MASVS levels references
  Document/0x04b-Mobile-App-Security-Testing.md
  Document/0x04f-Testing-Network-Communication.md
Labels: ignore-for-release
