Repository OWASP/mastg, pull requests merged in 2025-05, with the labels that each got.

#3265 Update 0x06b-iOS-Security-Testing.md fix wrong tool ref
  Document/0x06b-iOS-Security-Testing.md
Labels: iOS, fundamentals

#3177 Port MASTG-TEST-0032: Testing WebView Protocol Handlers (android)
  .github/workflows/config/url-checker-config.json
  Document/0x05a-Platform-Overview.md
  Document/0x05h-Testing-Platform-Interaction.md
  best-practices/MASTG-BEST-0010.md
  best-practices/MASTG-BEST-0011.md
  best-practices/MASTG-BEST-0012.md
  best-practices/MASTG-BEST-0013.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/AndroidManifest.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/AndroidManifest_reversed.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MASTG-DEMO-0029.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MastgTestWebView.kt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MastgTestWebView_reversed.java
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/evaluation.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/filepaths.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/output.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/run.sh
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/AndroidManifest.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/MASTG-DEMO-0030.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/MastgTestWebView.kt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/evaluation.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/filepaths.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/output.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/output_server.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/run.sh
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/script.js
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/server.py
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/AndroidManifest.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/MASTG-DEMO-0031.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/MastgTestWebView.kt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/evaluation.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/output.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/output_server.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/run.sh
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/AndroidManifest.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/AndroidManifest_reversed.xml
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/MASTG-DEMO-0032.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/MastgTestWebView.kt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/MastgTestWebView_reversed.java
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/evaluation.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/output.txt
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/run.sh
  rules/mastg-android-webview-allow-local-access.yml
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0250.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0251.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0252.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0253.md
  tests/android/MASVS-PLATFORM/MASTG-TEST-0032.md
Labels: Android, MASVS-PLATFORM, fundamentals

#3266 Update MASWE-0018.md draft
  weaknesses/MASVS-CRYPTO/MASWE-0018.md
Labels: ignore-for-release

#3267 Fix rule ref in MASTG-DEMO-0029
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MASTG-DEMO-0029.md
Labels: ignore-for-release

#3268 Update mkdocs.yml with new test and demo categories
  mkdocs.yml
Labels: ignore-for-release

#3226 Update pull request template with description section and guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: org, ignore-for-release

#3276 Fix id for MASTG-TEST-0252.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0252.md
Labels: ignore-for-release

#3278 Update create_dynamic_tables.py to search for issues and PRs
  docs/hooks/create_dynamic_tables.py
Labels: ignore-for-release

#3280 Enable new sections
  mkdocs.yml
Labels: ignore-for-release

#2912 Port MASTG-TEST-0042 MASTG-TEST-0085 and MASWE-0076 - Dependencies with Known Vulnerabilities (SBOM)
  .github/workflows/config/url-checker-config.json
  .vscode/settings.json
  demos/android/MASVS-CODE/MASTG-DEMO-0050/MASTG-DEMO-0050.md
  demos/android/MASVS-CODE/MASTG-DEMO-0050/build.gradle.kts
  demos/android/MASVS-CODE/MASTG-DEMO-0050/output.txt
  demos/android/MASVS-CODE/MASTG-DEMO-0050/run.sh
  demos/android/MASVS-CODE/MASTG-DEMO-0051/MASTG-DEMO-0051.md
  demos/android/MASVS-CODE/MASTG-DEMO-0051/output.json
  demos/android/MASVS-CODE/MASTG-DEMO-0051/run.sh
  demos/android/MASVS-CODE/MASTG-DEMO-0051/sbom.json
  demos/ios/MASVS-CODE/MASTG-DEMO-0052/MASTG-DEMO-0052.md
  demos/ios/MASVS-CODE/MASTG-DEMO-0052/Package.resolved
  demos/ios/MASVS-CODE/MASTG-DEMO-0052/output.txt
  demos/ios/MASVS-CODE/MASTG-DEMO-0052/run.sh
  demos/ios/MASVS-CODE/MASTG-DEMO-0053/MASTG-DEMO-0053.md
  demos/ios/MASVS-CODE/MASTG-DEMO-0053/output.txt
  demos/ios/MASVS-CODE/MASTG-DEMO-0053/run.sh
  techniques/android/MASTG-TECH-0129.md
  techniques/android/MASTG-TECH-0130.md
  techniques/android/MASTG-TECH-0131.md
  techniques/ios/MASTG-TECH-0082.md
  techniques/ios/MASTG-TECH-0132.md
  techniques/ios/MASTG-TECH-0133.md
  tests-beta/android/MASVS-CODE/MASTG-TEST-0272.md
  tests-beta/android/MASVS-CODE/MASTG-TEST-0274.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0273.md
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0275.md
  tests/android/MASVS-CODE/MASTG-TEST-0042.md
  tests/ios/MASVS-CODE/MASTG-TEST-0085.md
  tools/android/MASTG-TOOL-0130.md
  tools/generic/MASTG-TOOL-0131.md
  tools/generic/MASTG-TOOL-0132.md
  tools/generic/MASTG-TOOL-0133.md
  tools/generic/MASTG-TOOL-0134.md
  weaknesses/MASVS-CODE/MASWE-0076.md
Labels: MASVS-CODE, MASTG Refactor, MASWE

#3282 Update MASWE-0076 with Improved Content
  weaknesses/MASVS-CODE/MASWE-0076.md
Labels: MASVS-CODE, MASWE

#3286 Update index.md (fix link)
  docs/index.md
Labels: ignore-for-release

#3288 Update MASWE-0088 Draft
  weaknesses/MASVS-CODE/MASWE-0088.md
Labels: ignore-for-release

#3246 Add MASTG-TEST-0264, MASTG-TEST-0265, MASTG-DEMO-0038, MASTG-DEMO-0039
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0038/MASTG-DEMO-0038.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0038/output.txt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0038/run.sh
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0038/script.js
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/MASTG-DEMO-0039.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/MastgTest_reversed.java
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/output.txt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/run.sh
  rules/mastg-android-strictmode.yml
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0264.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0265.md
Labels: MASTG Refactor, almost-ready

#3293 Update MASWE-0043.md Draft
  weaknesses/MASVS-AUTH/MASWE-0043.md
Labels: ignore-for-release

#3256 Port MASTG-TEST-0064: Testing Local Authentication (ios)
  Document/Images/Techniques/0119-ObjectionBiometricsBypass.png
  Document/Images/Techniques/0119-ObjectionBiometricsBypassScreenshot.png
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/MASTG-DEMO-0041.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/MASTestApp
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/MastgTest.swift
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/insecureAuthenticationBiometricsApi.r2
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/output.asm
  demos/ios/MASVS-AUTH/MASTG-DEMO-0041/run.sh
  demos/ios/MASVS-AUTH/MASTG-DEMO-0042/MASTG-DEMO-0042.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0042/output.txt
  demos/ios/MASVS-AUTH/MASTG-DEMO-0042/run.sh
  demos/ios/MASVS-AUTH/MASTG-DEMO-0042/script.js
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/MASTG-DEMO-0043.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/MASTestApp
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/MastgTest.swift
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/biometricAuthenticationFallback.r2
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/output.asm
  demos/ios/MASVS-AUTH/MASTG-DEMO-0043/run.sh
  demos/ios/MASVS-AUTH/MASTG-DEMO-0044/MASTG-DEMO-0044.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0044/output.txt
  demos/ios/MASVS-AUTH/MASTG-DEMO-0044/run.sh
  demos/ios/MASVS-AUTH/MASTG-DEMO-0044/script.js
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/MASTG-DEMO-0045.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/MASTestApp
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/MastgTest.swift
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/biometricAuthenticationEnrollmentChange.r2
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/output.asm
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/run.sh
  demos/ios/MASVS-AUTH/MASTG-DEMO-0046/MASTG-DEMO-0046.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0046/output.txt
  demos/ios/MASVS-AUTH/MASTG-DEMO-0046/run.sh
  techniques/ios/MASTG-TECH-0119.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0266.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0267.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0268.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0269.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0270.md
  tests-beta/ios/MASVS-AUTH/MASTG-TEST-0271.md
  tests/ios/MASVS-AUTH/MASTG-TEST-0064.md
Labels: iOS, MASVS-AUTH, MASTG Refactor

#3296 FIx script ref in Update MASTG-DEMO-0045.md
  demos/ios/MASVS-AUTH/MASTG-DEMO-0045/MASTG-DEMO-0045.md
Labels: ignore-for-release

#3297 Update MASTG-TEST-0277.md fix ID
  tests-beta/ios/MASVS-PLATFORM/MASTG-TEST-0277.md
Labels: ignore-for-release

#3114 Update MASWE-0002 Draft Info
  weaknesses/MASVS-STORAGE/MASWE-0002.md
Labels: ignore-for-release
