Repository OWASP/mastg, pull requests merged in 2025-06, with the labels that each got.

#3303 Update .gitignore
  .gitignore
Labels: ignore-for-release

#3313 Update mkdocs.yml
  mkdocs.yml
Labels: ignore-for-release

#3314 Update donate.md (fix buttons style)
  docs/donate.md
Labels: ignore-for-release

#3320 Update mkdocs.yml - Disable new plugins
  mkdocs.yml
Labels: ignore-for-release

#3158 Add Deprecation Warnings about EncryptedFile and EncryptedSharedPreferences Android classes
  Document/0x05d-Testing-Data-Storage.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0001.md
  weaknesses/MASVS-STORAGE/MASWE-0006.md
  weaknesses/MASVS-STORAGE/MASWE-0007.md
Labels: Android, MASVS-STORAGE

#3047 Port MASTG-TEST-0054: Determining Whether Sensitive Data Is Shared with Third Parties (ios) (by @guardsquare)
  mkdocs.yml
  tests-beta/ios/MASVS-PRIVACY/MASTG-TEST-0281.md
  tests/ios/MASVS-STORAGE/MASTG-TEST-0054.md
Labels: iOS, MASVS-PRIVACY, MASTG Refactor

#3334 Update-MASTG-TECH-0117
  Document/0x05a-Platform-Overview.md
  techniques/android/MASTG-TECH-0117.md
Labels: Android, fundamentals

#3332 Add Filters for Tests
  docs/hooks/create_dynamic_tables.py
  docs/javascripts/datatables.js
  docs/javascripts/filter_tests.js
  mkdocs.yml
Labels: website

#3317 Refactor hooks, upgrade tags, fix requirements
  .vscode/launch.json
  docs/hooks/add-checklists-banner.py
  docs/hooks/add-cross-references.py
  docs/hooks/add-tags.py
  docs/hooks/create_dynamic_tables.py
  docs/hooks/edit_button_uri.py
  docs/hooks/extract-id-from-path.py
  docs/hooks/github_api.py
  docs/hooks/maswe-beta-banner.py
  docs/hooks/replace_snippets.py
  docs/hooks/resolve_references.py
  docs/hooks/update_git_info.py
  docs/hooks/update_titles.py
  docs/javascripts/filter_tests.js
  docs/javascripts/navigation.js
  docs/javascripts/tags.js
  docs/overrides/main.html
  docs/stylesheets/extra.css
  docs/tags.md
  mkdocs.yml
  run_web.sh
  src/scripts/requirements.txt
Labels: automation, website

#3338 Refine MASTG-TEST-0281 with better steps and criteria including new techniques MASTG-TECH-0136, MASTG-TECH-0137 and MASTG-TECH-0138
  techniques/ios/MASTG-TECH-0136.md
  techniques/ios/MASTG-TECH-0137.md
  techniques/ios/MASTG-TECH-0138.md
  tests-beta/ios/MASVS-PRIVACY/MASTG-TEST-0281.md
  tools/ios/MASTG-TOOL-0105.md
Labels: MASVS-PRIVACY, tests, ready-for-review

#3340 Refactor table search
  docs/javascripts/datatables.js
  docs/javascripts/filter_tests.js
Labels: website

#3344 Update MASTG-TECH-0137.md (fix note format)
  techniques/ios/MASTG-TECH-0137.md
Labels: ignore-for-release

#3347 Fix image copy
  src/scripts/structure_mastg.sh
Labels: ignore-for-release, website

#3349 Adds PlistBuddy and plistlib
  techniques/ios/MASTG-TECH-0137.md
  techniques/ios/MASTG-TECH-0138.md
  tools/ios/MASTG-TOOL-0135.md
  tools/ios/MASTG-TOOL-0136.md
Labels: iOS, tools

#3356 Remove references
  Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Labels: iOS, MASVS-RESILIENCE
