Repository OWASP/mastg, pull requests merged in 2025-03, with the labels that each got.

#3187 Update cross-references to MITM
  Document/0x04e-Testing-Authentication-and-Session-Management.md
  Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
  techniques/android/MASTG-TECH-0011.md
  techniques/generic/MASTG-TECH-0123.md
  techniques/generic/MASTG-TECH-0124.md
  techniques/ios/MASTG-TECH-0063.md
  tests/android/MASVS-NETWORK/MASTG-TEST-0021.md
  tests/android/MASVS-PLATFORM/MASTG-TEST-0031.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0004.md
  tests/ios/MASVS-CODE/MASTG-TEST-0080.md
  tests/ios/MASVS-CODE/MASTG-TEST-0085.md
  tests/ios/MASVS-NETWORK/MASTG-TEST-0067.md
  tests/ios/MASVS-STORAGE/MASTG-TEST-0054.md
  tools/network/MASTG-TOOL-0076.md
  tools/network/MASTG-TOOL-0077.md
  tools/network/MASTG-TOOL-0109.md
  weaknesses/MASVS-NETWORK/MASWE-0047.md
  weaknesses/MASVS-NETWORK/MASWE-0050.md
  weaknesses/MASVS-NETWORK/MASWE-0052.md
Labels: ignore-for-release

#3035 Port MASTG-TEST-0022: Testing Custom Certificate Stores and Certificate Pinning (android) (by @guardsquare)
  Document/0x05g-Testing-Network-Communication.md
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0242.md
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0243.md
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0244.md
  tests/android/MASVS-NETWORK/MASTG-TEST-0022.md
Labels: Android, MASVS-NETWORK, MASTG Refactor

#3194 MASTG v1->v2 MASTG-TEST-0061 Verifying the Configuration of Cryptographic Standard Algorithms (ios) and MASTG-TEST-0062 Testing Key Management (ios)
  tests/ios/MASVS-CRYPTO/MASTG-TEST-0061.md
  tests/ios/MASVS-CRYPTO/MASTG-TEST-0062.md
Labels: iOS, MASVS-CRYPTO, MASTG Refactor

#3113 Port MASTG-TEST-0012: Testing the Device-Access-Security Policy (android) (by @guardsquare)
  demos/android/MASVS-CODE/MASTG-DEMO-0025/MASTG-DEMO-0025.md
  demos/android/MASVS-CODE/MASTG-DEMO-0025/MastgTest.kt
  demos/android/MASVS-CODE/MASTG-DEMO-0025/MastgTest_reversed.java
  demos/android/MASVS-CODE/MASTG-DEMO-0025/output.txt
  demos/android/MASVS-CODE/MASTG-DEMO-0025/run.sh
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/AndroidManifest.xml
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/MASTG-DEMO-0027.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/MastgTest.kt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/output.txt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/run.sh
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/script.js
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/AndroidManifest.xml
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/AndroidManifest_reversed.xml
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/MASTG-DEMO-0028.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/MastgTest.kt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/MastgTest_reversed.java
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/output.txt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/run.sh
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/MASTG-DEMO-0024.md
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/MASTestApp
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/MastgTest.swift
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/isDevicePasscodeSet.r2
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/output.asm
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0024/run.sh
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/MASTG-DEMO-0026.md
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/MASTestApp
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/MastgTest.swift
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/output.txt
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/run.sh
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0026/script.js
  rules/mastg-android-device-passcode-present.yml
  rules/mastg-android-sdk-version.yml
  tests-beta/android/MASVS-CODE/MASTG-TEST-0245.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0247.md
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0249.md
  tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0246.md
  tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0248.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0012.md
  tests/ios/MASVS-AUTH/MASTG-TEST-0064.md
  weaknesses/MASVS-RESILIENCE/MASWE-0008.md
  weaknesses/MASVS-STORAGE/MASWE-0008.md
Labels: Android, MASVS-RESILIENCE, MASTG Refactor

#3205 Only run APK/IPA builds on changes demos in PRs only
  .github/workflows/build-android-demos.yml
  .github/workflows/build-ios-demos.yml
  demos/android/MASVS-CODE/MASTG-DEMO-0025/MASTG-DEMO-0025.md
  demos/ios/MASVS-CRYPTO/MASTG-DEMO-0011/MASTG-DEMO-0011.md
  docs/hooks/github_api.py
Labels: automation

#3207 [Drafts] Add demos and tests for WebView content access in Android
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MASTG-DEMO-0029.md
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/MASTG-DEMO-0030.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0250.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0251.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0252.md
  tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0253.md
Labels: ignore-for-release

#3209 Refactor draft banners for tests and demos
  docs/hooks/maswe-beta-banner.py
Labels: ignore-for-release

#3210 Update MASTG-DEMO-0030 ID
  demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/MASTG-DEMO-0030.md
Labels: ignore-for-release

#3211 Correct search query for issue or PR to include description
  docs/hooks/maswe-beta-banner.py
Labels: ignore-for-release

#3214 Fix Android demo build workflow by explicitly copying individual files
  .github/workflows/build-android-demos.yml
Labels: ignore-for-release

#3215 Update MASWE-0052.md (fix missing coma in cwes)
  weaknesses/MASVS-NETWORK/MASWE-0052.md
Labels: ignore-for-release, errata

#3028 Port MASTG-TEST-0009: Testing Backups for Sensitive Data (android) (by @guardsquare)
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/MASTG-DEMO-0020.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/backup_rules.xml
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/data_extraction_rules.xml
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/output_after.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/output_before.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/restored_files/profileInstalled
  demos/android/MASVS-STORAGE/MASTG-DEMO-0020/run.sh
  demos/android/MASVS-STORAGE/MASTG-DEMO-0033/MASTG-DEMO-0033.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/MASTG-DEMO-0034.md
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0216.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0009.md
  utils/mastg-android-backup-bmgr.sh
Labels: Android, MASVS-STORAGE, MASTG Refactor

#3216 Update MASTG-DEMO-0034.md (rm draft content)
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/MASTG-DEMO-0034.md
Labels: ignore-for-release

#3218 Update 0x02c-Acknowledgements.md ( add clarification)
  Document/0x02c-Acknowledgements.md
Labels: ignore-for-release

#3202 Add workflow to check for duplicate file IDs in PRs
  .github/scripts/check_duplicate_ids.py
  .github/workflows/check-duplicate-ids.yml
Labels: automation

#3076 Port MASTG-TEST-0024: Testing for App Permissions (android) (by @appknox)
  demos/android/MASVS-PRIVACY/MASTG-DEMO-0033/AndroidManifest.xml
  demos/android/MASVS-PRIVACY/MASTG-DEMO-0033/AndroidManifest_reversed.xml
  demos/android/MASVS-PRIVACY/MASTG-DEMO-0033/MASTG-DEMO-0033.md
  demos/android/MASVS-PRIVACY/MASTG-DEMO-0033/output.txt
  demos/android/MASVS-PRIVACY/MASTG-DEMO-0033/run.sh
  rules/mastg-android-dangerous-app-permissions.yaml
  techniques/android/MASTG-TECH-0126.md
  tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0254.md
  tests/android/MASVS-PLATFORM/MASTG-TEST-0024.md
Labels: Android, MASVS-PRIVACY, MASTG Refactor, changes-requested

#3219 Fix duplicate ID checker to handle PRs with no existing comments
  .github/workflows/check-duplicate-ids.yml
Labels: ignore-for-release

#3221 Fix demo IDs for backup and restore examples
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/MASTG-DEMO-0034.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/MASTG-DEMO-0035.md
Labels: ignore-for-release

#3222 Fix broken links
  mkdocs.yml
  techniques/ios/MASTG-TECH-0118.md
  tests-beta/android/MASVS-CODE/MASTG-TEST-0222.md
  tests-beta/android/MASVS-CODE/MASTG-TEST-0223.md
  tests-beta/android/MASVS-NETWORK/MASTG-TEST-0244.md
  tests/android/MASVS-NETWORK/MASTG-TEST-0019.md
  tests/ios/MASVS-NETWORK/MASTG-TEST-0065.md
  weaknesses/MASVS-NETWORK/MASWE-0047.md
Labels: ignore-for-release

#3225 Update development environment and settings
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  run_web.sh
Labels: ignore-for-release

#3227 Update 6_Add_a_Crackme.md - Fix links
  docs/contributing/6_Add_a_Crackme.md
Labels: ignore-for-release

#3097 Port MASTG-TEST-0082: Testing whether the App is Debuggable (ios) (by @appknox)
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0036/MASTG-DEMO-0036.md
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0036/MASTestApp
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0036/entitlements.plist
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0036/output.asm
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0036/run.sh
  tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0261.md
  tests/ios/MASVS-RESILIENCE/MASTG-TEST-0082.md
Labels: iOS, MASVS-RESILIENCE, MASTG Refactor, changes-done

#3055 Port MASTG-TEST-0006: Determining Whether the Keyboard Cache Is Disabled for Text Input Fields (android) (by @guardsquare)
  Document/0x05d-Testing-Data-Storage.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MASTG-DEMO-0024.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MastgTest_reversed.java
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/run.sh
  rules/mastg-android-non-caching-input-types.yml
  tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0258.md
  tests/android/MASVS-STORAGE/MASTG-TEST-0006.md
Labels: Android, MASVS-STORAGE, MASTG Refactor

#3240 Add terminal color customizations to VSCode settings
  .vscode/settings.json
Labels: ignore-for-release

#3241 Add draft for MASTG-TEST-0262: Backup Configurations Not Excluding Sensitive Data test
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0262.md
Labels: ignore-for-release

#3242 Port MASTG-TEST-0041: Testing for Debugging Code and Verbose Error Logging (android) (by @guardsquare)
  Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0037/MASTG-DEMO-0037.md
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0037/MastgTest.kt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0037/output.txt
  demos/android/MASVS-RESILIENCE/MASTG-DEMO-0037/run.sh
  tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0263.md
  tests/android/MASVS-RESILIENCE/MASTG-TEST-0041.md
  weaknesses/MASVS-RESILIENCE/MASWE-0094.md
Labels: Android, MASVS-CODE

#3217 Add MASTG-TEST-0262, MASTG-DEMO-0034 and MASTG-DEMO-0035 using adb backup and semgrep
  Document/0x05d-Testing-Data-Storage.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/MASTG-DEMO-0034.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0034/run.sh
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/MASTG-DEMO-0035.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/apps/org.owasp.mastestapp/f/profileInstalled
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/apps/org.owasp.mastestapp/f/secret.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0035/run.sh
  rules/mastg-android-backup-manifest.yml
  techniques/android/MASTG-TECH-0127.md
  techniques/android/MASTG-TECH-0128.md
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0216.md
  tests-beta/android/MASVS-STORAGE/MASTG-TEST-0262.md
  utils/mastg-android-backup-adb.sh
Labels: Android, MASVS-STORAGE

#3237 Enhance keyboard caching theory for Android (by @NowSecure)
  Document/0x05d-Testing-Data-Storage.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MASTG-DEMO-0024.md
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MastgTest.kt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/MastgTest_reversed.java
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/output.txt
  demos/android/MASVS-STORAGE/MASTG-DEMO-0024/run.sh
  rules/mastg-android-keyboard-cache-input-types.yml
  tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0258.md
Labels: Android, MASVS-STORAGE
