Repository OWASP/mastg, pull requests merged in 2025-01, with the labels that each got.

#2919 Add MASWE-0047, MASWE-0048, MASWE-0049, MASWE-0050, MASWE-0051, MASWE-0052
  weaknesses/MASVS-NETWORK/MASWE-0047.md
  weaknesses/MASVS-NETWORK/MASWE-0048.md
  weaknesses/MASVS-NETWORK/MASWE-0049.md
  weaknesses/MASVS-NETWORK/MASWE-0050.md
  weaknesses/MASVS-NETWORK/MASWE-0051.md
  weaknesses/MASVS-NETWORK/MASWE-0052.md
Labels: MASWE, almost-ready

#2913 Reverse Engineer Flutter Technique
  techniques/android/MASTG-TECH-0112.md
Labels: almost-ready

#3106 Update MASTG-TEST-0228 to remove a step that isn't needed
  tests-beta/ios/MASVS-CODE/MASTG-TEST-0228.md
Labels: tests

#3104 Update MASTG-TOOL-0064 Sileo (by @NVISOSecurity)
  tools/ios/MASTG-TOOL-0064.md
Labels: tools

#3026 Mark MASTG-TEST-0016 as covered by v2 (by @guardsquare)
  Document/0x05e-Testing-Cryptography.md
  best-practices/MASTG-BEST-0001.md
  tests-beta/android/MASVS-CRYPTO/MASTG-TEST-0204.md
  tests/android/MASVS-CRYPTO/MASTG-TEST-0016.md
  weaknesses/MASVS-CRYPTO/MASWE-0027.md
Labels: Android, MASVS-CRYPTO, MASTG Refactor, changes-requested

#3109 Update MASTG-DEMO-0021 (fix output.asm ref in .md)
  demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0021/MASTG-DEMO-0021.md
Labels: ignore-for-release

#2922 [MASWE-0023] Weak Padding
  weaknesses/MASVS-CRYPTO/MASWE-0023.md
Labels: changes-requested

#3118 Update MASTG-BEST-0004 - Add Link to Security recommendations for backups
  best-practices/MASTG-BEST-0004.md
  weaknesses/MASVS-STORAGE/MASWE-0003.md
  weaknesses/MASVS-STORAGE/MASWE-0004.md
Labels: best practices

#3122 added Eydle to donators
  Document/Images/Donators/donators.png
Labels: donation

#3125 Add GitHub Actions workflow to build iOS demos (by @NowSecure)
  .github/workflows/build-ios-demos.yml
Labels: iOS, automation, demos

#3126 Fix ios demos build
  .github/workflows/build-ios-demos.yml
Labels: ignore-for-release

#3128 Restore partial content in MASTG-TEST-0076 and fix outline in MASTG-TEST-0069
  tests/ios/MASVS-PLATFORM/MASTG-TEST-0069.md
  tests/ios/MASVS-PLATFORM/MASTG-TEST-0076.md
Labels: ignore-for-release

#3129 Update MASTG-TEST-0076 (minor fixes)
  tests/ios/MASVS-PLATFORM/MASTG-TEST-0076.md
  tests/ios/MASVS-PLATFORM/MASTG-TEST-0077.md
Labels: ignore-for-release

#3131 Update MASWE-0012 Draft
  weaknesses/MASVS-CRYPTO/MASWE-0012.md
Labels: ignore-for-release

#3132 Update MASWE-0058 Draft to add Ref
  weaknesses/MASVS-PLATFORM/MASWE-0058.md
Labels: ignore-for-release
