Repository OWASP/mastg, pull requests merged in 2025-02, with the labels that each got.

#2910 [MASWE-0020] Weak Encryption (by @appknox)
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MASTG-DEMO-0022.md
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MastgTest.kt
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/MastgTest_reversed.java
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/output.txt
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/run.sh
  demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MASTG-DEMO-0016.md
  demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MastgTest.kt
  demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/MastgTest_reversed.java
  demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/output.txt
  demos/android/MASVS-CRYPTO/MASTG_DEMO-0016/run.sh
  rules/mastg-android-weak-encryption-algorithms.yaml
  rules/mastg-android-weak-encryption-modes.yaml
  weaknesses/MASVS-CRYPTO/MASWE-0020.md
Labels: changes-requested

#3124 Update MASWE-0112: Add note about SDKs
  weaknesses/MASVS-PRIVACY/MASWE-0112.md
Labels: MASWE

#3147 Fixed Missing Reversed Java Code in the MASTG-DEMO-0017
  demos/android/MASVS-CRYPTO/MASTG-DEMO-0017/MASTG-DEMO-0017.md
Labels: ignore-for-release

#3100 Update IPA Installation Techniques and Tools (by @NVISOSecurity)
  Document/0x06b-iOS-Security-Testing.md
  Document/Images/Techniques/0056-Sideloadly.png
  techniques/ios/MASTG-TECH-0052.md
  techniques/ios/MASTG-TECH-0055.md
  techniques/ios/MASTG-TECH-0056.md
  techniques/ios/MASTG-TECH-0063.md
  techniques/ios/MASTG-TECH-0079.md
  techniques/ios/MASTG-TECH-0090.md
  techniques/ios/MASTG-TECH-0091.md
  techniques/ios/MASTG-TECH-0092.md
  techniques/ios/MASTG-TECH-0096.md
  techniques/ios/MASTG-TECH-0118.md
  tools/ios/MASTG-TOOL-0055.md
  tools/ios/MASTG-TOOL-0118.md
  tools/ios/MASTG-TOOL-0126.md
  tools/ios/MASTG-TOOL-0127.md
  tools/ios/MASTG-TOOL-0128.md
Labels: iOS, fundamentals

#3153 Update 0x02c-Acknowledgements.md
  Document/0x02c-Acknowledgements.md
Labels: ignore-for-release

#3119 Add MASWE-0117 - Inadequate Permission Management
  weaknesses/MASVS-PRIVACY/MASWE-0117.md
Labels: MASVS-PRIVACY, MASWE

#3170 Update Social Links
  docs/contact.md
  mkdocs.yml
Labels: org, website

#3182 Update contact.md
  docs/contact.md
  mkdocs.yml
Labels: ignore-for-release
